<?xml version="1.0" encoding="utf-8"?><Database Name="dbmalzeme" Class="MalzemeDbContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=OZGE;Initial Catalog=dbmalzeme;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dbmalzemeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tDgrTipi" Member="tDgrTipis">
    <Type Name="tDgrTipi">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DegerlemeTipi" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tUY" Member="tUYs">
    <Type Name="tUY">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UYAdi" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tKarMerkezi" Member="tKarMerkezis">
    <Type Name="tKarMerkezi">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KarMerkezi" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tKDV" Member="tKDVs">
    <Type Name="tKDV">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KDV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMalGrubu" Member="tMalGrubus">
    <Type Name="tMalGrubu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MalGrubu" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MalzemeTuruId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMipKrk" Member="tMipKrks">
    <Type Name="tMipKrk">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MipKrk" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMipSrmlu" Member="tMipSrmlus">
    <Type Name="tMipSrmlu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MipSorumlusu" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMlzBaslik" Member="tMlzBasliks">
    <Type Name="tMlzBaslik">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMalzemeTuru" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MalzemeNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MalzemeAdi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdUretimYeri" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MalzemeDurum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KaydedenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KayitTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GuncelleyenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GuncellemeTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdOnayDurum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMlzFin" Member="tMlzFins">
    <Type Name="tMlzFin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MalzemeBaslikId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdDegerlemetipi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdKarMerkezi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaliyetHesaplamaPartiBuyuklugu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdKDVOranı" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KaydedenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KayitTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GuncelleyenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GuncellemeTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMlzGenel" Member="tMlzGenels">
    <Type Name="tMlzGenel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MalzemeKodu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMalzemeTuru" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUretimYeri" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MalzemeKısaMetni" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DepoYeri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTemelOlcuBirimi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMalGrubu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMIPKarakteristligi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMIPSorumlusu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MIPPartiBuyuklugu" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdTedarikTuru" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UretimDenetimSorumlusu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UretimDenetimProfii" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DepoAdresi" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="EmliyetStogu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KaydedenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KayitTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GuncelleyenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GuncellemeTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMlzSat" Member="tMlzSats">
    <Type Name="tMlzSat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MalzemeBaslikId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FiyatBirimi" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PlanFiyat" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PlanFiyatTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="AsgariPartiBuyuklugu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YuvarlamaDegeri" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PlanlananTeslimatSuresi" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SASipaisMetni" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KaydedenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KayitTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GuncelleyenKullanici" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GuncellemeTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tMlzTurleri" Member="tMlzTurleris">
    <Type Name="tMlzTurleri">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MlzTuru" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tOnayDurum" Member="tOnayDurums">
    <Type Name="tOnayDurum">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OnayDurum" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tTdrkTuru" Member="tTdrkTurus">
    <Type Name="tTdrkTuru">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TedarikTuru" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tTOB" Member="tTOBs">
    <Type Name="tTOB">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TOB" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>