#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malzeme
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbmalzeme")]
	public partial class MalzemeDbContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttBolumler(tBolumler instance);
    partial void UpdatetBolumler(tBolumler instance);
    partial void DeletetBolumler(tBolumler instance);
    partial void InserttUY(tUY instance);
    partial void UpdatetUY(tUY instance);
    partial void DeletetUY(tUY instance);
    partial void InserttDgrTipi(tDgrTipi instance);
    partial void UpdatetDgrTipi(tDgrTipi instance);
    partial void DeletetDgrTipi(tDgrTipi instance);
    partial void InserttKarakterisrik(tKarakterisrik instance);
    partial void UpdatetKarakterisrik(tKarakterisrik instance);
    partial void DeletetKarakterisrik(tKarakterisrik instance);
    partial void InserttKarMerkezi(tKarMerkezi instance);
    partial void UpdatetKarMerkezi(tKarMerkezi instance);
    partial void DeletetKarMerkezi(tKarMerkezi instance);
    partial void InserttKDV(tKDV instance);
    partial void UpdatetKDV(tKDV instance);
    partial void DeletetKDV(tKDV instance);
    partial void InserttKullaniciBilgi(tKullaniciBilgi instance);
    partial void UpdatetKullaniciBilgi(tKullaniciBilgi instance);
    partial void DeletetKullaniciBilgi(tKullaniciBilgi instance);
    partial void InserttKullanicilar(tKullanicilar instance);
    partial void UpdatetKullanicilar(tKullanicilar instance);
    partial void DeletetKullanicilar(tKullanicilar instance);
    partial void InserttLoginGiris1(tLoginGiris1 instance);
    partial void UpdatetLoginGiris1(tLoginGiris1 instance);
    partial void DeletetLoginGiris1(tLoginGiris1 instance);
    partial void InserttMalGrubu(tMalGrubu instance);
    partial void UpdatetMalGrubu(tMalGrubu instance);
    partial void DeletetMalGrubu(tMalGrubu instance);
    partial void InserttMipKrk(tMipKrk instance);
    partial void UpdatetMipKrk(tMipKrk instance);
    partial void DeletetMipKrk(tMipKrk instance);
    partial void InserttMipSrmlu(tMipSrmlu instance);
    partial void UpdatetMipSrmlu(tMipSrmlu instance);
    partial void DeletetMipSrmlu(tMipSrmlu instance);
    partial void InserttMlzBaslik(tMlzBaslik instance);
    partial void UpdatetMlzBaslik(tMlzBaslik instance);
    partial void DeletetMlzBaslik(tMlzBaslik instance);
    partial void InserttMlzFin(tMlzFin instance);
    partial void UpdatetMlzFin(tMlzFin instance);
    partial void DeletetMlzFin(tMlzFin instance);
    partial void InserttMlzGenel(tMlzGenel instance);
    partial void UpdatetMlzGenel(tMlzGenel instance);
    partial void DeletetMlzGenel(tMlzGenel instance);
    partial void InserttMlzSat(tMlzSat instance);
    partial void UpdatetMlzSat(tMlzSat instance);
    partial void DeletetMlzSat(tMlzSat instance);
    partial void InserttMlzTurleri(tMlzTurleri instance);
    partial void UpdatetMlzTurleri(tMlzTurleri instance);
    partial void DeletetMlzTurleri(tMlzTurleri instance);
    partial void InserttOnayDurum(tOnayDurum instance);
    partial void UpdatetOnayDurum(tOnayDurum instance);
    partial void DeletetOnayDurum(tOnayDurum instance);
    partial void InserttSiniflar(tSiniflar instance);
    partial void UpdatetSiniflar(tSiniflar instance);
    partial void DeletetSiniflar(tSiniflar instance);
    partial void InserttTdrkTuru(tTdrkTuru instance);
    partial void UpdatetTdrkTuru(tTdrkTuru instance);
    partial void DeletetTdrkTuru(tTdrkTuru instance);
    partial void InserttTOB(tTOB instance);
    partial void UpdatetTOB(tTOB instance);
    partial void DeletetTOB(tTOB instance);
    #endregion
		
		public MalzemeDbContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbmalzemeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MalzemeDbContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MalzemeDbContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MalzemeDbContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MalzemeDbContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tBolumler> tBolumlers
		{
			get
			{
				return this.GetTable<tBolumler>();
			}
		}
		
		public System.Data.Linq.Table<tUY> tUYs
		{
			get
			{
				return this.GetTable<tUY>();
			}
		}
		
		public System.Data.Linq.Table<tDgrTipi> tDgrTipis
		{
			get
			{
				return this.GetTable<tDgrTipi>();
			}
		}
		
		public System.Data.Linq.Table<tKarakterisrik> tKarakterisriks
		{
			get
			{
				return this.GetTable<tKarakterisrik>();
			}
		}
		
		public System.Data.Linq.Table<tKarMerkezi> tKarMerkezis
		{
			get
			{
				return this.GetTable<tKarMerkezi>();
			}
		}
		
		public System.Data.Linq.Table<tKDV> tKDVs
		{
			get
			{
				return this.GetTable<tKDV>();
			}
		}
		
		public System.Data.Linq.Table<tKullaniciBilgi> tKullaniciBilgis
		{
			get
			{
				return this.GetTable<tKullaniciBilgi>();
			}
		}
		
		public System.Data.Linq.Table<tKullanicilar> tKullanicilars
		{
			get
			{
				return this.GetTable<tKullanicilar>();
			}
		}
		
		public System.Data.Linq.Table<tLoginGiris1> tLoginGiris1s
		{
			get
			{
				return this.GetTable<tLoginGiris1>();
			}
		}
		
		public System.Data.Linq.Table<tMalGrubu> tMalGrubus
		{
			get
			{
				return this.GetTable<tMalGrubu>();
			}
		}
		
		public System.Data.Linq.Table<tMipKrk> tMipKrks
		{
			get
			{
				return this.GetTable<tMipKrk>();
			}
		}
		
		public System.Data.Linq.Table<tMipSrmlu> tMipSrmlus
		{
			get
			{
				return this.GetTable<tMipSrmlu>();
			}
		}
		
		public System.Data.Linq.Table<tMlzBaslik> tMlzBasliks
		{
			get
			{
				return this.GetTable<tMlzBaslik>();
			}
		}
		
		public System.Data.Linq.Table<tMlzFin> tMlzFins
		{
			get
			{
				return this.GetTable<tMlzFin>();
			}
		}
		
		public System.Data.Linq.Table<tMlzGenel> tMlzGenels
		{
			get
			{
				return this.GetTable<tMlzGenel>();
			}
		}
		
		public System.Data.Linq.Table<tMlzSat> tMlzSats
		{
			get
			{
				return this.GetTable<tMlzSat>();
			}
		}
		
		public System.Data.Linq.Table<tMlzTurleri> tMlzTurleris
		{
			get
			{
				return this.GetTable<tMlzTurleri>();
			}
		}
		
		public System.Data.Linq.Table<tOnayDurum> tOnayDurums
		{
			get
			{
				return this.GetTable<tOnayDurum>();
			}
		}
		
		public System.Data.Linq.Table<tSiniflar> tSiniflars
		{
			get
			{
				return this.GetTable<tSiniflar>();
			}
		}
		
		public System.Data.Linq.Table<tTdrkTuru> tTdrkTurus
		{
			get
			{
				return this.GetTable<tTdrkTuru>();
			}
		}
		
		public System.Data.Linq.Table<tTOB> tTOBs
		{
			get
			{
				return this.GetTable<tTOB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tBolumler")]
	public partial class tBolumler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Bolumler;
		
		private EntitySet<tKullaniciBilgi> _tKullaniciBilgis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumlerChanging(string value);
    partial void OnBolumlerChanged();
    #endregion
		
		public tBolumler()
		{
			this._tKullaniciBilgis = new EntitySet<tKullaniciBilgi>(new Action<tKullaniciBilgi>(this.attach_tKullaniciBilgis), new Action<tKullaniciBilgi>(this.detach_tKullaniciBilgis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bolumler", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Bolumler
		{
			get
			{
				return this._Bolumler;
			}
			set
			{
				if ((this._Bolumler != value))
				{
					this.OnBolumlerChanging(value);
					this.SendPropertyChanging();
					this._Bolumler = value;
					this.SendPropertyChanged("Bolumler");
					this.OnBolumlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tBolumler_tKullaniciBilgi", Storage="_tKullaniciBilgis", ThisKey="Id", OtherKey="BolumlerID")]
		public EntitySet<tKullaniciBilgi> tKullaniciBilgis
		{
			get
			{
				return this._tKullaniciBilgis;
			}
			set
			{
				this._tKullaniciBilgis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tKullaniciBilgis(tKullaniciBilgi entity)
		{
			this.SendPropertyChanging();
			entity.tBolumler = this;
		}
		
		private void detach_tKullaniciBilgis(tKullaniciBilgi entity)
		{
			this.SendPropertyChanging();
			entity.tBolumler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tUY")]
	public partial class tUY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UYAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUYAdiChanging(string value);
    partial void OnUYAdiChanged();
    #endregion
		
		public tUY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYAdi", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UYAdi
		{
			get
			{
				return this._UYAdi;
			}
			set
			{
				if ((this._UYAdi != value))
				{
					this.OnUYAdiChanging(value);
					this.SendPropertyChanging();
					this._UYAdi = value;
					this.SendPropertyChanged("UYAdi");
					this.OnUYAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDgrTipi")]
	public partial class tDgrTipi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DegerlemeTipi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDegerlemeTipiChanging(string value);
    partial void OnDegerlemeTipiChanged();
    #endregion
		
		public tDgrTipi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegerlemeTipi", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DegerlemeTipi
		{
			get
			{
				return this._DegerlemeTipi;
			}
			set
			{
				if ((this._DegerlemeTipi != value))
				{
					this.OnDegerlemeTipiChanging(value);
					this.SendPropertyChanging();
					this._DegerlemeTipi = value;
					this.SendPropertyChanged("DegerlemeTipi");
					this.OnDegerlemeTipiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tKarakterisrik")]
	public partial class tKarakterisrik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KarakteristikAdi;
		
		private int _IdSiniflar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKarakteristikAdiChanging(string value);
    partial void OnKarakteristikAdiChanged();
    partial void OnIdSiniflarChanging(int value);
    partial void OnIdSiniflarChanged();
    #endregion
		
		public tKarakterisrik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KarakteristikAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KarakteristikAdi
		{
			get
			{
				return this._KarakteristikAdi;
			}
			set
			{
				if ((this._KarakteristikAdi != value))
				{
					this.OnKarakteristikAdiChanging(value);
					this.SendPropertyChanging();
					this._KarakteristikAdi = value;
					this.SendPropertyChanged("KarakteristikAdi");
					this.OnKarakteristikAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSiniflar", DbType="Int NOT NULL")]
		public int IdSiniflar
		{
			get
			{
				return this._IdSiniflar;
			}
			set
			{
				if ((this._IdSiniflar != value))
				{
					this.OnIdSiniflarChanging(value);
					this.SendPropertyChanging();
					this._IdSiniflar = value;
					this.SendPropertyChanged("IdSiniflar");
					this.OnIdSiniflarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tKarMerkezi")]
	public partial class tKarMerkezi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KarMerkezi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKarMerkeziChanging(string value);
    partial void OnKarMerkeziChanged();
    #endregion
		
		public tKarMerkezi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KarMerkezi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string KarMerkezi
		{
			get
			{
				return this._KarMerkezi;
			}
			set
			{
				if ((this._KarMerkezi != value))
				{
					this.OnKarMerkeziChanging(value);
					this.SendPropertyChanging();
					this._KarMerkezi = value;
					this.SendPropertyChanged("KarMerkezi");
					this.OnKarMerkeziChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tKDV")]
	public partial class tKDV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KDV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKDVChanging(string value);
    partial void OnKDVChanged();
    #endregion
		
		public tKDV()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KDV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string KDV
		{
			get
			{
				return this._KDV;
			}
			set
			{
				if ((this._KDV != value))
				{
					this.OnKDVChanging(value);
					this.SendPropertyChanging();
					this._KDV = value;
					this.SendPropertyChanged("KDV");
					this.OnKDVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tKullaniciBilgi")]
	public partial class tKullaniciBilgi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
		private string _Email;
		
		private int _BolumlerID;
		
		private EntityRef<tBolumler> _tBolumler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBolumlerIDChanging(int value);
    partial void OnBolumlerIDChanged();
    #endregion
		
		public tKullaniciBilgi()
		{
			this._tBolumler = default(EntityRef<tBolumler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumlerID", DbType="Int NOT NULL")]
		public int BolumlerID
		{
			get
			{
				return this._BolumlerID;
			}
			set
			{
				if ((this._BolumlerID != value))
				{
					if (this._tBolumler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBolumlerIDChanging(value);
					this.SendPropertyChanging();
					this._BolumlerID = value;
					this.SendPropertyChanged("BolumlerID");
					this.OnBolumlerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tBolumler_tKullaniciBilgi", Storage="_tBolumler", ThisKey="BolumlerID", OtherKey="Id", IsForeignKey=true)]
		public tBolumler tBolumler
		{
			get
			{
				return this._tBolumler.Entity;
			}
			set
			{
				tBolumler previousValue = this._tBolumler.Entity;
				if (((previousValue != value) 
							|| (this._tBolumler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tBolumler.Entity = null;
						previousValue.tKullaniciBilgis.Remove(this);
					}
					this._tBolumler.Entity = value;
					if ((value != null))
					{
						value.tKullaniciBilgis.Add(this);
						this._BolumlerID = value.Id;
					}
					else
					{
						this._BolumlerID = default(int);
					}
					this.SendPropertyChanged("tBolumler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tKullanicilar")]
	public partial class tKullanicilar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ad_Soyad;
		
		private int _Yetki_Grubu;
		
		private string _e_mail_Adesi;
		
		private EntityRef<tLoginGiris1> _tLoginGiris1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAd_SoyadChanging(string value);
    partial void OnAd_SoyadChanged();
    partial void OnYetki_GrubuChanging(int value);
    partial void OnYetki_GrubuChanged();
    partial void One_mail_AdesiChanging(string value);
    partial void One_mail_AdesiChanged();
    #endregion
		
		public tKullanicilar()
		{
			this._tLoginGiris1 = default(EntityRef<tLoginGiris1>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ad Soyad]", Storage="_Ad_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad_Soyad
		{
			get
			{
				return this._Ad_Soyad;
			}
			set
			{
				if ((this._Ad_Soyad != value))
				{
					this.OnAd_SoyadChanging(value);
					this.SendPropertyChanging();
					this._Ad_Soyad = value;
					this.SendPropertyChanged("Ad_Soyad");
					this.OnAd_SoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Yetki Grubu]", Storage="_Yetki_Grubu", DbType="Int NOT NULL")]
		public int Yetki_Grubu
		{
			get
			{
				return this._Yetki_Grubu;
			}
			set
			{
				if ((this._Yetki_Grubu != value))
				{
					this.OnYetki_GrubuChanging(value);
					this.SendPropertyChanging();
					this._Yetki_Grubu = value;
					this.SendPropertyChanged("Yetki_Grubu");
					this.OnYetki_GrubuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[e-mail Adesi]", Storage="_e_mail_Adesi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string e_mail_Adesi
		{
			get
			{
				return this._e_mail_Adesi;
			}
			set
			{
				if ((this._e_mail_Adesi != value))
				{
					this.One_mail_AdesiChanging(value);
					this.SendPropertyChanging();
					this._e_mail_Adesi = value;
					this.SendPropertyChanged("e_mail_Adesi");
					this.One_mail_AdesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tKullanicilar_tLoginGiris1", Storage="_tLoginGiris1", ThisKey="Id", OtherKey="Id", IsUnique=true, IsForeignKey=false)]
		public tLoginGiris1 tLoginGiris1
		{
			get
			{
				return this._tLoginGiris1.Entity;
			}
			set
			{
				tLoginGiris1 previousValue = this._tLoginGiris1.Entity;
				if (((previousValue != value) 
							|| (this._tLoginGiris1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tLoginGiris1.Entity = null;
						previousValue.tKullanicilar = null;
					}
					this._tLoginGiris1.Entity = value;
					if ((value != null))
					{
						value.tKullanicilar = this;
					}
					this.SendPropertyChanged("tLoginGiris1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tLoginGiris1")]
	public partial class tLoginGiris1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Kullanici_adi;
		
		private int _Sifre;
		
		private EntityRef<tKullanicilar> _tKullanicilar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKullanici_adiChanging(string value);
    partial void OnKullanici_adiChanged();
    partial void OnSifreChanging(int value);
    partial void OnSifreChanged();
    #endregion
		
		public tLoginGiris1()
		{
			this._tKullanicilar = default(EntityRef<tKullanicilar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._tKullanicilar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Kullanici adi]", Storage="_Kullanici_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kullanici_adi
		{
			get
			{
				return this._Kullanici_adi;
			}
			set
			{
				if ((this._Kullanici_adi != value))
				{
					this.OnKullanici_adiChanging(value);
					this.SendPropertyChanging();
					this._Kullanici_adi = value;
					this.SendPropertyChanged("Kullanici_adi");
					this.OnKullanici_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="Int NOT NULL")]
		public int Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tKullanicilar_tLoginGiris1", Storage="_tKullanicilar", ThisKey="Id", OtherKey="Id", IsForeignKey=true)]
		public tKullanicilar tKullanicilar
		{
			get
			{
				return this._tKullanicilar.Entity;
			}
			set
			{
				tKullanicilar previousValue = this._tKullanicilar.Entity;
				if (((previousValue != value) 
							|| (this._tKullanicilar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tKullanicilar.Entity = null;
						previousValue.tLoginGiris1 = null;
					}
					this._tKullanicilar.Entity = value;
					if ((value != null))
					{
						value.tLoginGiris1 = this;
						this._Id = value.Id;
					}
					else
					{
						this._Id = default(int);
					}
					this.SendPropertyChanged("tKullanicilar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMalGrubu")]
	public partial class tMalGrubu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MalGrubu;
		
		private int _MalzemeTuruId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMalGrubuChanging(string value);
    partial void OnMalGrubuChanged();
    partial void OnMalzemeTuruIdChanging(int value);
    partial void OnMalzemeTuruIdChanged();
    #endregion
		
		public tMalGrubu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalGrubu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MalGrubu
		{
			get
			{
				return this._MalGrubu;
			}
			set
			{
				if ((this._MalGrubu != value))
				{
					this.OnMalGrubuChanging(value);
					this.SendPropertyChanging();
					this._MalGrubu = value;
					this.SendPropertyChanged("MalGrubu");
					this.OnMalGrubuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeTuruId", DbType="Int NOT NULL")]
		public int MalzemeTuruId
		{
			get
			{
				return this._MalzemeTuruId;
			}
			set
			{
				if ((this._MalzemeTuruId != value))
				{
					this.OnMalzemeTuruIdChanging(value);
					this.SendPropertyChanging();
					this._MalzemeTuruId = value;
					this.SendPropertyChanged("MalzemeTuruId");
					this.OnMalzemeTuruIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMipKrk")]
	public partial class tMipKrk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MipKrk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMipKrkChanging(string value);
    partial void OnMipKrkChanged();
    #endregion
		
		public tMipKrk()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MipKrk", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MipKrk
		{
			get
			{
				return this._MipKrk;
			}
			set
			{
				if ((this._MipKrk != value))
				{
					this.OnMipKrkChanging(value);
					this.SendPropertyChanging();
					this._MipKrk = value;
					this.SendPropertyChanged("MipKrk");
					this.OnMipKrkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMipSrmlu")]
	public partial class tMipSrmlu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MipSorumlusu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMipSorumlusuChanging(string value);
    partial void OnMipSorumlusuChanged();
    #endregion
		
		public tMipSrmlu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MipSorumlusu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MipSorumlusu
		{
			get
			{
				return this._MipSorumlusu;
			}
			set
			{
				if ((this._MipSorumlusu != value))
				{
					this.OnMipSorumlusuChanging(value);
					this.SendPropertyChanging();
					this._MipSorumlusu = value;
					this.SendPropertyChanged("MipSorumlusu");
					this.OnMipSorumlusuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMlzBaslik")]
	public partial class tMlzBaslik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdMalzemeTuru;
		
		private string _MalzemeNo;
		
		private string _MalzemeAdi;
		
		private int _IdUretimYeri;
		
		private string _MalzemeDurum;
		
		private string _KaydedenKullanici;
		
		private System.DateTime _KayitTarihi;
		
		private string _GuncelleyenKullanici;
		
		private System.DateTime _GuncellemeTarihi;
		
		private int _IdOnayDurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdMalzemeTuruChanging(int value);
    partial void OnIdMalzemeTuruChanged();
    partial void OnMalzemeNoChanging(string value);
    partial void OnMalzemeNoChanged();
    partial void OnMalzemeAdiChanging(string value);
    partial void OnMalzemeAdiChanged();
    partial void OnIdUretimYeriChanging(int value);
    partial void OnIdUretimYeriChanged();
    partial void OnMalzemeDurumChanging(string value);
    partial void OnMalzemeDurumChanged();
    partial void OnKaydedenKullaniciChanging(string value);
    partial void OnKaydedenKullaniciChanged();
    partial void OnKayitTarihiChanging(System.DateTime value);
    partial void OnKayitTarihiChanged();
    partial void OnGuncelleyenKullaniciChanging(string value);
    partial void OnGuncelleyenKullaniciChanged();
    partial void OnGuncellemeTarihiChanging(System.DateTime value);
    partial void OnGuncellemeTarihiChanged();
    partial void OnIdOnayDurumChanging(int value);
    partial void OnIdOnayDurumChanged();
    #endregion
		
		public tMlzBaslik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalzemeTuru", DbType="Int NOT NULL")]
		public int IdMalzemeTuru
		{
			get
			{
				return this._IdMalzemeTuru;
			}
			set
			{
				if ((this._IdMalzemeTuru != value))
				{
					this.OnIdMalzemeTuruChanging(value);
					this.SendPropertyChanging();
					this._IdMalzemeTuru = value;
					this.SendPropertyChanged("IdMalzemeTuru");
					this.OnIdMalzemeTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MalzemeNo
		{
			get
			{
				return this._MalzemeNo;
			}
			set
			{
				if ((this._MalzemeNo != value))
				{
					this.OnMalzemeNoChanging(value);
					this.SendPropertyChanging();
					this._MalzemeNo = value;
					this.SendPropertyChanged("MalzemeNo");
					this.OnMalzemeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MalzemeAdi
		{
			get
			{
				return this._MalzemeAdi;
			}
			set
			{
				if ((this._MalzemeAdi != value))
				{
					this.OnMalzemeAdiChanging(value);
					this.SendPropertyChanging();
					this._MalzemeAdi = value;
					this.SendPropertyChanged("MalzemeAdi");
					this.OnMalzemeAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUretimYeri", DbType="Int NOT NULL")]
		public int IdUretimYeri
		{
			get
			{
				return this._IdUretimYeri;
			}
			set
			{
				if ((this._IdUretimYeri != value))
				{
					this.OnIdUretimYeriChanging(value);
					this.SendPropertyChanging();
					this._IdUretimYeri = value;
					this.SendPropertyChanged("IdUretimYeri");
					this.OnIdUretimYeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeDurum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MalzemeDurum
		{
			get
			{
				return this._MalzemeDurum;
			}
			set
			{
				if ((this._MalzemeDurum != value))
				{
					this.OnMalzemeDurumChanging(value);
					this.SendPropertyChanging();
					this._MalzemeDurum = value;
					this.SendPropertyChanged("MalzemeDurum");
					this.OnMalzemeDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KaydedenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string KaydedenKullanici
		{
			get
			{
				return this._KaydedenKullanici;
			}
			set
			{
				if ((this._KaydedenKullanici != value))
				{
					this.OnKaydedenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._KaydedenKullanici = value;
					this.SendPropertyChanged("KaydedenKullanici");
					this.OnKaydedenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarihi", DbType="Date NOT NULL")]
		public System.DateTime KayitTarihi
		{
			get
			{
				return this._KayitTarihi;
			}
			set
			{
				if ((this._KayitTarihi != value))
				{
					this.OnKayitTarihiChanging(value);
					this.SendPropertyChanging();
					this._KayitTarihi = value;
					this.SendPropertyChanged("KayitTarihi");
					this.OnKayitTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncelleyenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GuncelleyenKullanici
		{
			get
			{
				return this._GuncelleyenKullanici;
			}
			set
			{
				if ((this._GuncelleyenKullanici != value))
				{
					this.OnGuncelleyenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._GuncelleyenKullanici = value;
					this.SendPropertyChanged("GuncelleyenKullanici");
					this.OnGuncelleyenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncellemeTarihi", DbType="Date NOT NULL")]
		public System.DateTime GuncellemeTarihi
		{
			get
			{
				return this._GuncellemeTarihi;
			}
			set
			{
				if ((this._GuncellemeTarihi != value))
				{
					this.OnGuncellemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._GuncellemeTarihi = value;
					this.SendPropertyChanged("GuncellemeTarihi");
					this.OnGuncellemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOnayDurum", DbType="Int NOT NULL")]
		public int IdOnayDurum
		{
			get
			{
				return this._IdOnayDurum;
			}
			set
			{
				if ((this._IdOnayDurum != value))
				{
					this.OnIdOnayDurumChanging(value);
					this.SendPropertyChanging();
					this._IdOnayDurum = value;
					this.SendPropertyChanged("IdOnayDurum");
					this.OnIdOnayDurumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMlzFin")]
	public partial class tMlzFin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _MalzemeBaslikId;
		
		private int _IdDegerlemetipi;
		
		private int _IdKarMerkezi;
		
		private string _MaliyetHesaplamaPartiBuyuklugu;
		
		private int _IdKDVOranı;
		
		private string _KaydedenKullanici;
		
		private System.DateTime _KayitTarihi;
		
		private string _GuncelleyenKullanici;
		
		private System.DateTime _GuncellemeTarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMalzemeBaslikIdChanging(int value);
    partial void OnMalzemeBaslikIdChanged();
    partial void OnIdDegerlemetipiChanging(int value);
    partial void OnIdDegerlemetipiChanged();
    partial void OnIdKarMerkeziChanging(int value);
    partial void OnIdKarMerkeziChanged();
    partial void OnMaliyetHesaplamaPartiBuyukluguChanging(string value);
    partial void OnMaliyetHesaplamaPartiBuyukluguChanged();
    partial void OnIdKDVOranıChanging(int value);
    partial void OnIdKDVOranıChanged();
    partial void OnKaydedenKullaniciChanging(string value);
    partial void OnKaydedenKullaniciChanged();
    partial void OnKayitTarihiChanging(System.DateTime value);
    partial void OnKayitTarihiChanged();
    partial void OnGuncelleyenKullaniciChanging(string value);
    partial void OnGuncelleyenKullaniciChanged();
    partial void OnGuncellemeTarihiChanging(System.DateTime value);
    partial void OnGuncellemeTarihiChanged();
    #endregion
		
		public tMlzFin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeBaslikId", DbType="Int NOT NULL")]
		public int MalzemeBaslikId
		{
			get
			{
				return this._MalzemeBaslikId;
			}
			set
			{
				if ((this._MalzemeBaslikId != value))
				{
					this.OnMalzemeBaslikIdChanging(value);
					this.SendPropertyChanging();
					this._MalzemeBaslikId = value;
					this.SendPropertyChanged("MalzemeBaslikId");
					this.OnMalzemeBaslikIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDegerlemetipi", DbType="Int NOT NULL")]
		public int IdDegerlemetipi
		{
			get
			{
				return this._IdDegerlemetipi;
			}
			set
			{
				if ((this._IdDegerlemetipi != value))
				{
					this.OnIdDegerlemetipiChanging(value);
					this.SendPropertyChanging();
					this._IdDegerlemetipi = value;
					this.SendPropertyChanged("IdDegerlemetipi");
					this.OnIdDegerlemetipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKarMerkezi", DbType="Int NOT NULL")]
		public int IdKarMerkezi
		{
			get
			{
				return this._IdKarMerkezi;
			}
			set
			{
				if ((this._IdKarMerkezi != value))
				{
					this.OnIdKarMerkeziChanging(value);
					this.SendPropertyChanging();
					this._IdKarMerkezi = value;
					this.SendPropertyChanged("IdKarMerkezi");
					this.OnIdKarMerkeziChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaliyetHesaplamaPartiBuyuklugu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaliyetHesaplamaPartiBuyuklugu
		{
			get
			{
				return this._MaliyetHesaplamaPartiBuyuklugu;
			}
			set
			{
				if ((this._MaliyetHesaplamaPartiBuyuklugu != value))
				{
					this.OnMaliyetHesaplamaPartiBuyukluguChanging(value);
					this.SendPropertyChanging();
					this._MaliyetHesaplamaPartiBuyuklugu = value;
					this.SendPropertyChanged("MaliyetHesaplamaPartiBuyuklugu");
					this.OnMaliyetHesaplamaPartiBuyukluguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKDVOranı", DbType="Int NOT NULL")]
		public int IdKDVOranı
		{
			get
			{
				return this._IdKDVOranı;
			}
			set
			{
				if ((this._IdKDVOranı != value))
				{
					this.OnIdKDVOranıChanging(value);
					this.SendPropertyChanging();
					this._IdKDVOranı = value;
					this.SendPropertyChanged("IdKDVOranı");
					this.OnIdKDVOranıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KaydedenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string KaydedenKullanici
		{
			get
			{
				return this._KaydedenKullanici;
			}
			set
			{
				if ((this._KaydedenKullanici != value))
				{
					this.OnKaydedenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._KaydedenKullanici = value;
					this.SendPropertyChanged("KaydedenKullanici");
					this.OnKaydedenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarihi", DbType="Date NOT NULL")]
		public System.DateTime KayitTarihi
		{
			get
			{
				return this._KayitTarihi;
			}
			set
			{
				if ((this._KayitTarihi != value))
				{
					this.OnKayitTarihiChanging(value);
					this.SendPropertyChanging();
					this._KayitTarihi = value;
					this.SendPropertyChanged("KayitTarihi");
					this.OnKayitTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncelleyenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GuncelleyenKullanici
		{
			get
			{
				return this._GuncelleyenKullanici;
			}
			set
			{
				if ((this._GuncelleyenKullanici != value))
				{
					this.OnGuncelleyenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._GuncelleyenKullanici = value;
					this.SendPropertyChanged("GuncelleyenKullanici");
					this.OnGuncelleyenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncellemeTarihi", DbType="Date NOT NULL")]
		public System.DateTime GuncellemeTarihi
		{
			get
			{
				return this._GuncellemeTarihi;
			}
			set
			{
				if ((this._GuncellemeTarihi != value))
				{
					this.OnGuncellemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._GuncellemeTarihi = value;
					this.SendPropertyChanged("GuncellemeTarihi");
					this.OnGuncellemeTarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMlzGenel")]
	public partial class tMlzGenel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _MalzemeKodu;
		
		private int _IdMalzemeTuru;
		
		private int _IdUretimYeri;
		
		private string _MalzemeKısaMetni;
		
		private string _DepoYeri;
		
		private int _IdTemelOlcuBirimi;
		
		private int _IdMalGrubu;
		
		private int _IdMIPKarakteristligi;
		
		private int _IdMIPSorumlusu;
		
		private string _MIPPartiBuyuklugu;
		
		private int _IdTedarikTuru;
		
		private string _UretimDenetimSorumlusu;
		
		private string _UretimDenetimProfii;
		
		private string _DepoAdresi;
		
		private string _EmliyetStogu;
		
		private string _KaydedenKullanici;
		
		private System.DateTime _KayitTarihi;
		
		private string _GuncelleyenKullanici;
		
		private System.DateTime _GuncellemeTarihi;
		
		private int _IdOnayDurumu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMalzemeKoduChanging(int value);
    partial void OnMalzemeKoduChanged();
    partial void OnIdMalzemeTuruChanging(int value);
    partial void OnIdMalzemeTuruChanged();
    partial void OnIdUretimYeriChanging(int value);
    partial void OnIdUretimYeriChanged();
    partial void OnMalzemeKısaMetniChanging(string value);
    partial void OnMalzemeKısaMetniChanged();
    partial void OnDepoYeriChanging(string value);
    partial void OnDepoYeriChanged();
    partial void OnIdTemelOlcuBirimiChanging(int value);
    partial void OnIdTemelOlcuBirimiChanged();
    partial void OnIdMalGrubuChanging(int value);
    partial void OnIdMalGrubuChanged();
    partial void OnIdMIPKarakteristligiChanging(int value);
    partial void OnIdMIPKarakteristligiChanged();
    partial void OnIdMIPSorumlusuChanging(int value);
    partial void OnIdMIPSorumlusuChanged();
    partial void OnMIPPartiBuyukluguChanging(string value);
    partial void OnMIPPartiBuyukluguChanged();
    partial void OnIdTedarikTuruChanging(int value);
    partial void OnIdTedarikTuruChanged();
    partial void OnUretimDenetimSorumlusuChanging(string value);
    partial void OnUretimDenetimSorumlusuChanged();
    partial void OnUretimDenetimProfiiChanging(string value);
    partial void OnUretimDenetimProfiiChanged();
    partial void OnDepoAdresiChanging(string value);
    partial void OnDepoAdresiChanged();
    partial void OnEmliyetStoguChanging(string value);
    partial void OnEmliyetStoguChanged();
    partial void OnKaydedenKullaniciChanging(string value);
    partial void OnKaydedenKullaniciChanged();
    partial void OnKayitTarihiChanging(System.DateTime value);
    partial void OnKayitTarihiChanged();
    partial void OnGuncelleyenKullaniciChanging(string value);
    partial void OnGuncelleyenKullaniciChanged();
    partial void OnGuncellemeTarihiChanging(System.DateTime value);
    partial void OnGuncellemeTarihiChanged();
    partial void OnIdOnayDurumuChanging(int value);
    partial void OnIdOnayDurumuChanged();
    #endregion
		
		public tMlzGenel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeKodu", DbType="Int NOT NULL")]
		public int MalzemeKodu
		{
			get
			{
				return this._MalzemeKodu;
			}
			set
			{
				if ((this._MalzemeKodu != value))
				{
					this.OnMalzemeKoduChanging(value);
					this.SendPropertyChanging();
					this._MalzemeKodu = value;
					this.SendPropertyChanged("MalzemeKodu");
					this.OnMalzemeKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalzemeTuru", DbType="Int NOT NULL")]
		public int IdMalzemeTuru
		{
			get
			{
				return this._IdMalzemeTuru;
			}
			set
			{
				if ((this._IdMalzemeTuru != value))
				{
					this.OnIdMalzemeTuruChanging(value);
					this.SendPropertyChanging();
					this._IdMalzemeTuru = value;
					this.SendPropertyChanged("IdMalzemeTuru");
					this.OnIdMalzemeTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUretimYeri", DbType="Int NOT NULL")]
		public int IdUretimYeri
		{
			get
			{
				return this._IdUretimYeri;
			}
			set
			{
				if ((this._IdUretimYeri != value))
				{
					this.OnIdUretimYeriChanging(value);
					this.SendPropertyChanging();
					this._IdUretimYeri = value;
					this.SendPropertyChanged("IdUretimYeri");
					this.OnIdUretimYeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeKısaMetni", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string MalzemeKısaMetni
		{
			get
			{
				return this._MalzemeKısaMetni;
			}
			set
			{
				if ((this._MalzemeKısaMetni != value))
				{
					this.OnMalzemeKısaMetniChanging(value);
					this.SendPropertyChanging();
					this._MalzemeKısaMetni = value;
					this.SendPropertyChanged("MalzemeKısaMetni");
					this.OnMalzemeKısaMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepoYeri", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DepoYeri
		{
			get
			{
				return this._DepoYeri;
			}
			set
			{
				if ((this._DepoYeri != value))
				{
					this.OnDepoYeriChanging(value);
					this.SendPropertyChanging();
					this._DepoYeri = value;
					this.SendPropertyChanged("DepoYeri");
					this.OnDepoYeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTemelOlcuBirimi", DbType="Int NOT NULL")]
		public int IdTemelOlcuBirimi
		{
			get
			{
				return this._IdTemelOlcuBirimi;
			}
			set
			{
				if ((this._IdTemelOlcuBirimi != value))
				{
					this.OnIdTemelOlcuBirimiChanging(value);
					this.SendPropertyChanging();
					this._IdTemelOlcuBirimi = value;
					this.SendPropertyChanged("IdTemelOlcuBirimi");
					this.OnIdTemelOlcuBirimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMalGrubu", DbType="Int NOT NULL")]
		public int IdMalGrubu
		{
			get
			{
				return this._IdMalGrubu;
			}
			set
			{
				if ((this._IdMalGrubu != value))
				{
					this.OnIdMalGrubuChanging(value);
					this.SendPropertyChanging();
					this._IdMalGrubu = value;
					this.SendPropertyChanged("IdMalGrubu");
					this.OnIdMalGrubuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMIPKarakteristligi", DbType="Int NOT NULL")]
		public int IdMIPKarakteristligi
		{
			get
			{
				return this._IdMIPKarakteristligi;
			}
			set
			{
				if ((this._IdMIPKarakteristligi != value))
				{
					this.OnIdMIPKarakteristligiChanging(value);
					this.SendPropertyChanging();
					this._IdMIPKarakteristligi = value;
					this.SendPropertyChanged("IdMIPKarakteristligi");
					this.OnIdMIPKarakteristligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMIPSorumlusu", DbType="Int NOT NULL")]
		public int IdMIPSorumlusu
		{
			get
			{
				return this._IdMIPSorumlusu;
			}
			set
			{
				if ((this._IdMIPSorumlusu != value))
				{
					this.OnIdMIPSorumlusuChanging(value);
					this.SendPropertyChanging();
					this._IdMIPSorumlusu = value;
					this.SendPropertyChanged("IdMIPSorumlusu");
					this.OnIdMIPSorumlusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIPPartiBuyuklugu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MIPPartiBuyuklugu
		{
			get
			{
				return this._MIPPartiBuyuklugu;
			}
			set
			{
				if ((this._MIPPartiBuyuklugu != value))
				{
					this.OnMIPPartiBuyukluguChanging(value);
					this.SendPropertyChanging();
					this._MIPPartiBuyuklugu = value;
					this.SendPropertyChanged("MIPPartiBuyuklugu");
					this.OnMIPPartiBuyukluguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTedarikTuru", DbType="Int NOT NULL")]
		public int IdTedarikTuru
		{
			get
			{
				return this._IdTedarikTuru;
			}
			set
			{
				if ((this._IdTedarikTuru != value))
				{
					this.OnIdTedarikTuruChanging(value);
					this.SendPropertyChanging();
					this._IdTedarikTuru = value;
					this.SendPropertyChanged("IdTedarikTuru");
					this.OnIdTedarikTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UretimDenetimSorumlusu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UretimDenetimSorumlusu
		{
			get
			{
				return this._UretimDenetimSorumlusu;
			}
			set
			{
				if ((this._UretimDenetimSorumlusu != value))
				{
					this.OnUretimDenetimSorumlusuChanging(value);
					this.SendPropertyChanging();
					this._UretimDenetimSorumlusu = value;
					this.SendPropertyChanged("UretimDenetimSorumlusu");
					this.OnUretimDenetimSorumlusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UretimDenetimProfii", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UretimDenetimProfii
		{
			get
			{
				return this._UretimDenetimProfii;
			}
			set
			{
				if ((this._UretimDenetimProfii != value))
				{
					this.OnUretimDenetimProfiiChanging(value);
					this.SendPropertyChanging();
					this._UretimDenetimProfii = value;
					this.SendPropertyChanged("UretimDenetimProfii");
					this.OnUretimDenetimProfiiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepoAdresi", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string DepoAdresi
		{
			get
			{
				return this._DepoAdresi;
			}
			set
			{
				if ((this._DepoAdresi != value))
				{
					this.OnDepoAdresiChanging(value);
					this.SendPropertyChanging();
					this._DepoAdresi = value;
					this.SendPropertyChanged("DepoAdresi");
					this.OnDepoAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmliyetStogu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmliyetStogu
		{
			get
			{
				return this._EmliyetStogu;
			}
			set
			{
				if ((this._EmliyetStogu != value))
				{
					this.OnEmliyetStoguChanging(value);
					this.SendPropertyChanging();
					this._EmliyetStogu = value;
					this.SendPropertyChanged("EmliyetStogu");
					this.OnEmliyetStoguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KaydedenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string KaydedenKullanici
		{
			get
			{
				return this._KaydedenKullanici;
			}
			set
			{
				if ((this._KaydedenKullanici != value))
				{
					this.OnKaydedenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._KaydedenKullanici = value;
					this.SendPropertyChanged("KaydedenKullanici");
					this.OnKaydedenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarihi", DbType="Date NOT NULL")]
		public System.DateTime KayitTarihi
		{
			get
			{
				return this._KayitTarihi;
			}
			set
			{
				if ((this._KayitTarihi != value))
				{
					this.OnKayitTarihiChanging(value);
					this.SendPropertyChanging();
					this._KayitTarihi = value;
					this.SendPropertyChanged("KayitTarihi");
					this.OnKayitTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncelleyenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GuncelleyenKullanici
		{
			get
			{
				return this._GuncelleyenKullanici;
			}
			set
			{
				if ((this._GuncelleyenKullanici != value))
				{
					this.OnGuncelleyenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._GuncelleyenKullanici = value;
					this.SendPropertyChanged("GuncelleyenKullanici");
					this.OnGuncelleyenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncellemeTarihi", DbType="Date NOT NULL")]
		public System.DateTime GuncellemeTarihi
		{
			get
			{
				return this._GuncellemeTarihi;
			}
			set
			{
				if ((this._GuncellemeTarihi != value))
				{
					this.OnGuncellemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._GuncellemeTarihi = value;
					this.SendPropertyChanged("GuncellemeTarihi");
					this.OnGuncellemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOnayDurumu", DbType="Int NOT NULL")]
		public int IdOnayDurumu
		{
			get
			{
				return this._IdOnayDurumu;
			}
			set
			{
				if ((this._IdOnayDurumu != value))
				{
					this.OnIdOnayDurumuChanging(value);
					this.SendPropertyChanging();
					this._IdOnayDurumu = value;
					this.SendPropertyChanged("IdOnayDurumu");
					this.OnIdOnayDurumuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMlzSat")]
	public partial class tMlzSat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _MalzemeBaslikId;
		
		private string _FiyatBirimi;
		
		private string _PlanFiyat;
		
		private System.DateTime _PlanFiyatTarihi;
		
		private string _AsgariPartiBuyuklugu;
		
		private string _YuvarlamaDegeri;
		
		private string _PlanlananTeslimatSuresi;
		
		private string _SASipaisMetni;
		
		private string _KaydedenKullanici;
		
		private System.DateTime _KayitTarihi;
		
		private string _GuncelleyenKullanici;
		
		private System.DateTime _GuncellemeTarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMalzemeBaslikIdChanging(int value);
    partial void OnMalzemeBaslikIdChanged();
    partial void OnFiyatBirimiChanging(string value);
    partial void OnFiyatBirimiChanged();
    partial void OnPlanFiyatChanging(string value);
    partial void OnPlanFiyatChanged();
    partial void OnPlanFiyatTarihiChanging(System.DateTime value);
    partial void OnPlanFiyatTarihiChanged();
    partial void OnAsgariPartiBuyukluguChanging(string value);
    partial void OnAsgariPartiBuyukluguChanged();
    partial void OnYuvarlamaDegeriChanging(string value);
    partial void OnYuvarlamaDegeriChanged();
    partial void OnPlanlananTeslimatSuresiChanging(string value);
    partial void OnPlanlananTeslimatSuresiChanged();
    partial void OnSASipaisMetniChanging(string value);
    partial void OnSASipaisMetniChanged();
    partial void OnKaydedenKullaniciChanging(string value);
    partial void OnKaydedenKullaniciChanged();
    partial void OnKayitTarihiChanging(System.DateTime value);
    partial void OnKayitTarihiChanged();
    partial void OnGuncelleyenKullaniciChanging(string value);
    partial void OnGuncelleyenKullaniciChanged();
    partial void OnGuncellemeTarihiChanging(System.DateTime value);
    partial void OnGuncellemeTarihiChanged();
    #endregion
		
		public tMlzSat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalzemeBaslikId", DbType="Int NOT NULL")]
		public int MalzemeBaslikId
		{
			get
			{
				return this._MalzemeBaslikId;
			}
			set
			{
				if ((this._MalzemeBaslikId != value))
				{
					this.OnMalzemeBaslikIdChanging(value);
					this.SendPropertyChanging();
					this._MalzemeBaslikId = value;
					this.SendPropertyChanged("MalzemeBaslikId");
					this.OnMalzemeBaslikIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiyatBirimi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FiyatBirimi
		{
			get
			{
				return this._FiyatBirimi;
			}
			set
			{
				if ((this._FiyatBirimi != value))
				{
					this.OnFiyatBirimiChanging(value);
					this.SendPropertyChanging();
					this._FiyatBirimi = value;
					this.SendPropertyChanged("FiyatBirimi");
					this.OnFiyatBirimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanFiyat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PlanFiyat
		{
			get
			{
				return this._PlanFiyat;
			}
			set
			{
				if ((this._PlanFiyat != value))
				{
					this.OnPlanFiyatChanging(value);
					this.SendPropertyChanging();
					this._PlanFiyat = value;
					this.SendPropertyChanged("PlanFiyat");
					this.OnPlanFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanFiyatTarihi", DbType="Date NOT NULL")]
		public System.DateTime PlanFiyatTarihi
		{
			get
			{
				return this._PlanFiyatTarihi;
			}
			set
			{
				if ((this._PlanFiyatTarihi != value))
				{
					this.OnPlanFiyatTarihiChanging(value);
					this.SendPropertyChanging();
					this._PlanFiyatTarihi = value;
					this.SendPropertyChanged("PlanFiyatTarihi");
					this.OnPlanFiyatTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsgariPartiBuyuklugu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AsgariPartiBuyuklugu
		{
			get
			{
				return this._AsgariPartiBuyuklugu;
			}
			set
			{
				if ((this._AsgariPartiBuyuklugu != value))
				{
					this.OnAsgariPartiBuyukluguChanging(value);
					this.SendPropertyChanging();
					this._AsgariPartiBuyuklugu = value;
					this.SendPropertyChanged("AsgariPartiBuyuklugu");
					this.OnAsgariPartiBuyukluguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YuvarlamaDegeri", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string YuvarlamaDegeri
		{
			get
			{
				return this._YuvarlamaDegeri;
			}
			set
			{
				if ((this._YuvarlamaDegeri != value))
				{
					this.OnYuvarlamaDegeriChanging(value);
					this.SendPropertyChanging();
					this._YuvarlamaDegeri = value;
					this.SendPropertyChanged("YuvarlamaDegeri");
					this.OnYuvarlamaDegeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanlananTeslimatSuresi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PlanlananTeslimatSuresi
		{
			get
			{
				return this._PlanlananTeslimatSuresi;
			}
			set
			{
				if ((this._PlanlananTeslimatSuresi != value))
				{
					this.OnPlanlananTeslimatSuresiChanging(value);
					this.SendPropertyChanging();
					this._PlanlananTeslimatSuresi = value;
					this.SendPropertyChanged("PlanlananTeslimatSuresi");
					this.OnPlanlananTeslimatSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SASipaisMetni", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SASipaisMetni
		{
			get
			{
				return this._SASipaisMetni;
			}
			set
			{
				if ((this._SASipaisMetni != value))
				{
					this.OnSASipaisMetniChanging(value);
					this.SendPropertyChanging();
					this._SASipaisMetni = value;
					this.SendPropertyChanged("SASipaisMetni");
					this.OnSASipaisMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KaydedenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string KaydedenKullanici
		{
			get
			{
				return this._KaydedenKullanici;
			}
			set
			{
				if ((this._KaydedenKullanici != value))
				{
					this.OnKaydedenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._KaydedenKullanici = value;
					this.SendPropertyChanged("KaydedenKullanici");
					this.OnKaydedenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarihi", DbType="Date NOT NULL")]
		public System.DateTime KayitTarihi
		{
			get
			{
				return this._KayitTarihi;
			}
			set
			{
				if ((this._KayitTarihi != value))
				{
					this.OnKayitTarihiChanging(value);
					this.SendPropertyChanging();
					this._KayitTarihi = value;
					this.SendPropertyChanged("KayitTarihi");
					this.OnKayitTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncelleyenKullanici", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GuncelleyenKullanici
		{
			get
			{
				return this._GuncelleyenKullanici;
			}
			set
			{
				if ((this._GuncelleyenKullanici != value))
				{
					this.OnGuncelleyenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._GuncelleyenKullanici = value;
					this.SendPropertyChanged("GuncelleyenKullanici");
					this.OnGuncelleyenKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuncellemeTarihi", DbType="Date NOT NULL")]
		public System.DateTime GuncellemeTarihi
		{
			get
			{
				return this._GuncellemeTarihi;
			}
			set
			{
				if ((this._GuncellemeTarihi != value))
				{
					this.OnGuncellemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._GuncellemeTarihi = value;
					this.SendPropertyChanged("GuncellemeTarihi");
					this.OnGuncellemeTarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMlzTurleri")]
	public partial class tMlzTurleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MlzTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMlzTuruChanging(string value);
    partial void OnMlzTuruChanged();
    #endregion
		
		public tMlzTurleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MlzTuru", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MlzTuru
		{
			get
			{
				return this._MlzTuru;
			}
			set
			{
				if ((this._MlzTuru != value))
				{
					this.OnMlzTuruChanging(value);
					this.SendPropertyChanging();
					this._MlzTuru = value;
					this.SendPropertyChanged("MlzTuru");
					this.OnMlzTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tOnayDurum")]
	public partial class tOnayDurum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _OnayDurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOnayDurumChanging(string value);
    partial void OnOnayDurumChanged();
    #endregion
		
		public tOnayDurum()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnayDurum", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string OnayDurum
		{
			get
			{
				return this._OnayDurum;
			}
			set
			{
				if ((this._OnayDurum != value))
				{
					this.OnOnayDurumChanging(value);
					this.SendPropertyChanging();
					this._OnayDurum = value;
					this.SendPropertyChanged("OnayDurum");
					this.OnOnayDurumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tSiniflar")]
	public partial class tSiniflar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _SinifAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSinifAdiChanging(string value);
    partial void OnSinifAdiChanged();
    #endregion
		
		public tSiniflar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinifAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SinifAdi
		{
			get
			{
				return this._SinifAdi;
			}
			set
			{
				if ((this._SinifAdi != value))
				{
					this.OnSinifAdiChanging(value);
					this.SendPropertyChanging();
					this._SinifAdi = value;
					this.SendPropertyChanged("SinifAdi");
					this.OnSinifAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTdrkTuru")]
	public partial class tTdrkTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TedarikTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTedarikTuruChanging(string value);
    partial void OnTedarikTuruChanged();
    #endregion
		
		public tTdrkTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TedarikTuru", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TedarikTuru
		{
			get
			{
				return this._TedarikTuru;
			}
			set
			{
				if ((this._TedarikTuru != value))
				{
					this.OnTedarikTuruChanging(value);
					this.SendPropertyChanging();
					this._TedarikTuru = value;
					this.SendPropertyChanged("TedarikTuru");
					this.OnTedarikTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTOB")]
	public partial class tTOB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TOB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTOBChanging(string value);
    partial void OnTOBChanged();
    #endregion
		
		public tTOB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOB", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TOB
		{
			get
			{
				return this._TOB;
			}
			set
			{
				if ((this._TOB != value))
				{
					this.OnTOBChanging(value);
					this.SendPropertyChanging();
					this._TOB = value;
					this.SendPropertyChanged("TOB");
					this.OnTOBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
